# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy-core" do
  name "fastdeploy-core"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy-core"
  version "1.0.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fd"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_#{version}_darwin_amd64.tar.gz"
      sha256 "99fa0d5c9e303c64430e9544823ecc2adb7f5f85a3c18d225bde836617ea33d1"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_#{version}_darwin_arm64.tar.gz"
      sha256 "b07c64d9651159fe08b9644414335d4c9dd92925670ddda0d4399d6245f49499"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_#{version}_linux_amd64.tar.gz"
      sha256 "1c3392adc6db02930eccc50f69aa05aadd6712a500b6228742285e640243edc2"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_#{version}_linux_arm64.tar.gz"
      sha256 "cee9a531f888b08080809fc6212de3fe0fa61f0e6b32e4fc3705a0f355216c9b"
    end
  end

  # No zap stanza required
end
