# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy" do
  name "fastdeploy"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy"
  version "1.0.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fd"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_amd64.tar.gz"
      sha256 "acfef474d7b7e059809a3191f5026e0239c2f1387af0ec26bf4d2143fd6272fc"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_arm64.tar.gz"
      sha256 "48c486417a45ca35cfff13d8ef29b908c3262c5dd8deaf594e0fa6962f61512a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_amd64.tar.gz"
      sha256 "cf036e3db060ce868c3d17f9c50acf11c351104f53387d984864bd9f8a74f67b"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_arm64.tar.gz"
      sha256 "fb49c44c75cb27565f6aad14243b629fed13204d16c9efc947c141a74141e8e2"
    end
  end

  # No zap stanza required
end
