# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy" do
  name "fastdeploy"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy"
  version "1.0.13"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fd"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_darwin_amd64.tar.gz"
      sha256 "f1bddf3ea77922aedc140b713d11a23af9e0ffde60b224620581f2964d00ce89"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_darwin_arm64.tar.gz"
      sha256 "d94ac274acc742d5c39b29edce5713efa3f7bcfd2bc8d854ebd6da40be76c4eb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_linux_amd64.tar.gz"
      sha256 "d210c063eca93b225558de6064b29d9e3548c283493d57edd20c82ddde0db22b"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_linux_arm64.tar.gz"
      sha256 "e7862516d14fec0e0fb2df538e68d1dba8b72ba6d838055e0318baefe57acd7e"
    end
  end

  # No zap stanza required
end
