# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy" do
  name "fastdeploy"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fd"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_amd64.tar.gz"
      sha256 "50566d7150368365a7f1263b64a67913a4c60ec0bfb960e367ba357ad1fcf64c"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_darwin_arm64.tar.gz"
      sha256 "c388111e5ebd7bbe4c38073ad2332ee33eb9721a9533340dc5a2c165d1965eef"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_amd64.tar.gz"
      sha256 "8136c2fa271a69c741541d2450196b169db8d3e83b13484023dd9e8bac8c8f4e"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy/releases/download/v#{version}/fastdeploy_#{version}_linux_arm64.tar.gz"
      sha256 "a576d3641bcad6d35d2fbb9475993f4f622c56e120932a50d071da348f1d8112"
    end
  end

  # No zap stanza required
end
