# This file was generated by GoReleaser. DO NOT EDIT.
cask "fastdeploy-core" do
  name "fastdeploy-core"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/fastdeploy-core"
  version "1.0.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fd"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_darwin_amd64.tar.gz"
      sha256 "ce5109d010f1e4398556209677979ebd8abd946799b5cf0fc6f3cea278512440"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_darwin_arm64.tar.gz"
      sha256 "f5567a23ee939571a2e7b9eb1a1faceed04359cbd67a93daa2bb52f112d56da8"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_linux_amd64.tar.gz"
      sha256 "02f3153fcbfdcb24b77df01a67e1fd5dfc5159faf08d3ce94617ecd42ffc62e5"
    end
    on_arm do
      url "https://github.com/jairoprogramador/fastdeploy-core/releases/download/v#{version}/fastdeploy-core_linux_arm64.tar.gz"
      sha256 "52d962499bdf86ab768f16efe9ff8ee3fec28f747dbec2df432c29857d7b8961"
    end
  end

  # No zap stanza required
end
