# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexc" do
  name "vexc"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"
  version "1.0.17"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexc"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_amd64.tar.gz"
      sha256 "778696e9a586696b4db8705c9bf9c6614bd1386af31fe8005a8a47577ea1eff2"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_arm64.tar.gz"
      sha256 "c8337de10c361049b52abfeab382753a3bae0d1a5111a0ee3fcb9ef443b20846"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_amd64.tar.gz"
      sha256 "c27350ed8f358ee7007319bcfbee970785b7ab9a1490d81ea506afc09ca26b2c"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_arm64.tar.gz"
      sha256 "69c5472dc5106c0550c31bad059f9dc6722e4cab9b86360410acd0f91a42d5a0"
    end
  end

  # No zap stanza required
end
