# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexc" do
  name "vexc"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex"
  version "1.0.18"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexc"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_amd64.tar.gz"
      sha256 "4e1cbd941efd54d579c72c7947a2db69eeacdb1970a09a23d0e8eeecb8ca657d"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_darwin_arm64.tar.gz"
      sha256 "a35529ea991021daa4f65d88f783ba396386b067d3654245e54999c283779c14"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_amd64.tar.gz"
      sha256 "3717c22f10bb872d364faaf25ec40e3b681733696b49f72da4db276ac3f58b8f"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex/releases/download/v#{version}/vexc_linux_arm64.tar.gz"
      sha256 "89f65292d00ca1cd97956c7c89678da241169b34567a9891f5240aef616f76e2"
    end
  end

  # No zap stanza required
end
