# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexd" do
  version "1.0.21"

  on_macos do
    on_intel do
      sha256 "59bfcf63c3c72fb5386b26d399aff62661eab3cd3cd11497d8acb8a5cbb1a299"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b322ea4e2dd619c65f3e630039902b63c4ae76506c3540c3024360adcf3e31b"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e1d530cfd66d28b597fbac779993824ba1b30258dc135decf8b7d3c6f39fea09"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8e99d3ac01041538e8d462b48d47a57c9030a85be11322b34ea90dacba108e0a"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_arm64.tar.gz"
    end
  end

  name "vexd"
  desc "Daemon de ejecución para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-engine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexd"

  # No zap stanza required

end
