# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexd" do
  version "1.0.23"

  on_macos do
    on_intel do
      sha256 "28bf14be99db14607617837123d49a4f738806dfe55742df94548ec5662808ab"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ed3e92123b4f5de5d4d2b3901849b999f8f4f8cabe8c5764ccea57f0a86a28cd"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6cc50f99ccb327e58afcb1ead34cd0da047a1e42041b5dd2a9e144225cb109e0"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ea7fbba705a784a2cb47a92edead8adb47bfbce385c8ff07d7f5672a612190a1"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_arm64.tar.gz"
    end
  end

  name "vexd"
  desc "Daemon de ejecución para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-engine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexd"

  # No zap stanza required

end
