# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexd" do
  version "1.0.31"

  on_macos do
    on_intel do
      sha256 "2cd856ae57c07b1d10a47ee79784c9da8d2bcae65f44755247ceb01dbd8b0a53"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6eed07521d481818024ab4050e9a66634f0fac998fdcbba7fededf6ecb681c6a"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "74ac7e5c54c98d82a467d62e5e3b2ae07580b3aae41efd9c2a7e7f8935c46d6a"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fcb77f096eee5300fbad9a9a1fb7b41b9e9d03649ad446ea742f0672072432c"
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexd_linux_arm64.tar.gz"
    end
  end

  name "vexd"
  desc "Daemon de ejecución para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-engine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexd"

  # No zap stanza required

end
