# This file was generated by GoReleaser. DO NOT EDIT.
cask "vexe" do
  version "1.0.19"

  on_macos do
    on_intel do
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexe_darwin_amd64.tar.gz"
      sha256 "f7f9b56536cda7b91f86b7f13d560c73ad19b8a9c7c86070536fc6f1c3c4568e"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexe_darwin_arm64.tar.gz"
      sha256 "de9f8f20eb1a789e046efb3cee944a844f71851351e10adf8ebd55be0b19211e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexe_linux_amd64.tar.gz"
      sha256 "52f4f0b91346a76d9e49019bdaa817463ad52b74541f2c800b9ef4ed2744baf7"
    end
    on_arm do
      url "https://github.com/jairoprogramador/vex-engine/releases/download/v#{version}/vexe_linux_arm64.tar.gz"
      sha256 "4403b4f69490d949c30230c20e0ea82a5f9ae86cf6e5e303e30d8c2f4772f1c0"
    end
  end

  name "vexe"
  desc "CLI multiplataforma para despliegues automáticos y rápidos de aplicaciones"
  homepage "https://github.com/jairoprogramador/vex-engine"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vexe"

  # No zap stanza required

end
